// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DSI-Core","status":true,"description":"v1.99 A helper plugin for DSI plugins.","parameters":{"showDevTool:bool":"true","autoUpdate:bool":"false"}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}},
{"name":"GALV_CamControlMZ","status":true,"description":"(v.1.7) Allows greater control over where the game camera is focused. View documentation for plugin commands.","parameters":{"useZoom":"true","bZoom":"1"}},
{"name":"DSI-Astar","status":true,"description":"(v1.0) A star pathfind plugin by dsiver144","parameters":{}},
{"name":"DSI-TBS-1-DataStruct","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-1-GameUtils","status":true,"description":"(v1.0) A custom plugin by dsiver144","parameters":{"testParam:number":"144"}},
{"name":"DSI-TBS-1-BattleUnitManager","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-SpriteUtils","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleTile","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleUnit","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-3-TacticleUnitController","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleCursor","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleMap","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleRange","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-TacticleRangeManager","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-2-Sprite_TacticleUnitSelection","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-3-TacticleUnitCommandWindow","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-3-TacticleUnitActionListWindow","status":true,"description":"","parameters":{}},
{"name":"DSI-TBS-3-TacticleUnitSelectionWindow","status":true,"description":"","parameters":{}},
{"name":"DSI-TacticalBattleSystem","status":true,"description":"(v1.0) A custom plugin by dsiver144","parameters":{"testParam2:number":"144"}}
];
