// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"DSI-Core","status":true,"description":"v1.99 A helper plugin for DSI plugins.","parameters":{"showDevTool:bool":"true","autoUpdate:bool":"true"}},
{"name":"GALV_CharacterFramesMZ","status":true,"description":"Enables map character sheets to have more frames per character.","parameters":{"fSpeedMod":"f * 0.8","fileSymbol":"%"}},
{"name":"DSI-Astar","status":true,"description":"(v1.0) A star pathfind plugin by dsiver144","parameters":{}},
{"name":"DSI-TacticalBattleSystem","status":true,"description":"(v1.0) A custom plugin by dsiver144","parameters":{"testParam:number":"144"}}
];
